compdb_dir: ../build

templates: # paths to template files
  header: ../generator/templates/header.inja
  enum: ../generator/templates/enum.inja
  object: ../generator/templates/object.inja

input:
  - ../generator/config.h

output_dir: ../generator/self_generated
