name: CTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          mkdir build && cd build &&
          cmake ..
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DENABLE_GENERATOR:STRING=ON
          -DLLVM_TARGETS_TO_BUILD:STRING=X86

      - name: Build
        run: >
          cmake --build ./build -j 2
          -t er_gen tests

      - name: Test
        working-directory: ./build
        run: ctest --rerun-failed --output-on-failure
